"""PostgreSQL initial schema

Revision ID: 0001_postgresql_initial
Revises:
Create Date: 2026-08-16 18:07:38.361690

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_postgresql_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blocklist",
        sa.Column("telegram_user_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("blocked_by_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("telegram_user_id"),
    )
    op.create_table(
        "inbound_updates",
        sa.Column("telegram_update_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column(
            "ordering_key", sa.String(length=64), server_default="legacy:global", nullable=False
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claim_token", sa.String(length=36), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("telegram_update_id"),
    )
    op.create_index(
        "ix_inbound_updates_claim",
        "inbound_updates",
        ["status", "next_attempt_at", "telegram_update_id"],
        unique=False,
    )
    op.create_index(
        "ix_inbound_updates_ordering",
        "inbound_updates",
        ["ordering_key", "status", "telegram_update_id"],
        unique=False,
    )
    op.create_index(
        "ix_inbound_updates_stale", "inbound_updates", ["status", "claimed_at"], unique=False
    )
    op.create_table(
        "operator_dashboard_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=True),
        sa.Column("period", sa.String(length=16), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "quick_responses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("created_by_display_name", sa.String(length=255), nullable=True),
        sa.Column("created_by_username", sa.String(length=255), nullable=True),
        sa.Column("source_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("source_message_id", sa.BigInteger(), nullable=False),
        sa.Column("published_message_id", sa.BigInteger(), nullable=True),
        sa.Column("publication_format_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("invalid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("warning_message_id", sa.BigInteger(), nullable=True),
        sa.Column("deleted_by_telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("published_message_id", name="uq_quick_responses_published_message"),
        sa.UniqueConstraint(
            "source_chat_id", "source_message_id", name="uq_quick_responses_source"
        ),
    )
    op.create_index(
        "ix_quick_responses_state_deadline",
        "quick_responses",
        ["state", "invalid_until", "id"],
        unique=False,
    )
    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=1000), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("remnawave_user_uuid", sa.String(length=36), nullable=True),
        sa.Column("topic_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("topic_provisioning_token", sa.String(length=36), nullable=True),
        sa.Column("topic_provisioning_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_cycle", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("topic_id"),
        sa.UniqueConstraint("topic_provisioning_token"),
        sa.UniqueConstraint("user_id", "channel", name="uq_ticket_user_channel"),
    )
    op.create_index(
        "ix_tickets_status_last_activity", "tickets", ["status", "last_activity_at"], unique=False
    )
    op.create_index("ix_tickets_status_updated", "tickets", ["status", "updated_at"], unique=False)
    op.create_table(
        "user_identities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=320), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_id", name="uq_identity_provider_external"),
    )
    op.create_table(
        "delivery_outbox",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=512), nullable=False),
        sa.Column("direction", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claim_token", sa.String(length=36), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_message_id", sa.BigInteger(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        "ix_delivery_outbox_claim",
        "delivery_outbox",
        ["status", "next_attempt_at", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_delivery_outbox_stale", "delivery_outbox", ["status", "claimed_at"], unique=False
    )
    op.create_index(
        "ix_delivery_outbox_ticket_direction_status",
        "delivery_outbox",
        ["ticket_id", "direction", "status"],
        unique=False,
    )
    op.create_index(
        "ix_delivery_outbox_ticket_status_created",
        "delivery_outbox",
        ["ticket_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "operator_actions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=True),
        sa.Column("operator_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=512), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", sa.String(length=64), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        "ix_operator_actions_result_created",
        "operator_actions",
        ["result", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_operator_actions_ticket_action_result",
        "operator_actions",
        ["ticket_id", "action", "result"],
        unique=False,
    )
    op.create_index(
        "uq_operator_actions_unresolved_ticket",
        "operator_actions",
        ["ticket_id"],
        unique=True,
        postgresql_where=sa.text("result IN ('started', 'unknown') AND action LIKE 'remnawave_%%'"),
    )
    op.create_table(
        "support_blocks",
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("blocked_by_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ticket_id"),
    )
    op.create_table(
        "ticket_lifecycle_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("close_cycle", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ticket_lifecycle_event_time",
        "ticket_lifecycle_events",
        ["event_type", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_ticket_lifecycle_ticket_time",
        "ticket_lifecycle_events",
        ["ticket_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "ticket_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("direction", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("media", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("suppressed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sensitive", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("rating_cycle", sa.Integer(), nullable=True),
        sa.Column("source_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("source_message_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "direction", "source_chat_id", "source_message_id", name="uq_ticket_message_source"
        ),
        sa.UniqueConstraint(
            "ticket_id", "channel", "rating_cycle", name="uq_ticket_message_rating_cycle"
        ),
    )
    op.create_index(
        "ix_ticket_messages_direction_channel_created",
        "ticket_messages",
        ["direction", "channel", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_ticket_messages_sensitive_created",
        "ticket_messages",
        ["sensitive", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_ticket_messages_ticket_created",
        "ticket_messages",
        ["ticket_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "media_assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("storage_path", sa.String(length=512), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["ticket_messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id"),
        sa.UniqueConstraint("storage_path", name="uq_media_asset_storage_path"),
    )
    op.create_index(
        "ix_media_assets_ticket_created", "media_assets", ["ticket_id", "created_at"], unique=False
    )
    op.create_table(
        "notification_outbox",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("operator_action_id", sa.String(length=36), nullable=True),
        sa.Column("idempotency_key", sa.String(length=512), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("destination", sa.String(length=64), nullable=False),
        sa.Column("recipient_identity_provider", sa.String(length=32), nullable=False),
        sa.Column("recipient_identity_value", sa.String(length=320), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claim_token", sa.String(length=36), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["operator_action_id"], ["operator_actions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
        sa.UniqueConstraint("operator_action_id"),
    )
    op.create_index(
        "ix_notification_outbox_claim",
        "notification_outbox",
        ["status", "next_attempt_at", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_outbox_stale",
        "notification_outbox",
        ["status", "claimed_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_outbox_ticket_status_created",
        "notification_outbox",
        ["ticket_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "reconciliation_outbox",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=512), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=True),
        sa.Column("operator_action_id", sa.String(length=36), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claim_token", sa.String(length=36), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["operator_action_id"], ["operator_actions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
        sa.UniqueConstraint("operator_action_id"),
    )
    op.create_index(
        "ix_reconciliation_claim",
        "reconciliation_outbox",
        ["status", "next_attempt_at", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_reconciliation_stale", "reconciliation_outbox", ["status", "claimed_at"], unique=False
    )
    op.create_index(
        "ix_reconciliation_ticket_status_created",
        "reconciliation_outbox",
        ["ticket_id", "status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reconciliation_ticket_status_created", table_name="reconciliation_outbox")
    op.drop_index("ix_reconciliation_stale", table_name="reconciliation_outbox")
    op.drop_index("ix_reconciliation_claim", table_name="reconciliation_outbox")
    op.drop_table("reconciliation_outbox")
    op.drop_index("ix_notification_outbox_ticket_status_created", table_name="notification_outbox")
    op.drop_index("ix_notification_outbox_stale", table_name="notification_outbox")
    op.drop_index("ix_notification_outbox_claim", table_name="notification_outbox")
    op.drop_table("notification_outbox")
    op.drop_index("ix_media_assets_ticket_created", table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_index("ix_ticket_messages_ticket_created", table_name="ticket_messages")
    op.drop_index("ix_ticket_messages_sensitive_created", table_name="ticket_messages")
    op.drop_index("ix_ticket_messages_direction_channel_created", table_name="ticket_messages")
    op.drop_table("ticket_messages")
    op.drop_index("ix_ticket_lifecycle_ticket_time", table_name="ticket_lifecycle_events")
    op.drop_index("ix_ticket_lifecycle_event_time", table_name="ticket_lifecycle_events")
    op.drop_table("ticket_lifecycle_events")
    op.drop_table("support_blocks")
    op.drop_index(
        "uq_operator_actions_unresolved_ticket",
        table_name="operator_actions",
        postgresql_where=sa.text("result IN ('started', 'unknown') AND action LIKE 'remnawave_%%'"),
    )
    op.drop_index("ix_operator_actions_ticket_action_result", table_name="operator_actions")
    op.drop_index("ix_operator_actions_result_created", table_name="operator_actions")
    op.drop_table("operator_actions")
    op.drop_index("ix_delivery_outbox_ticket_status_created", table_name="delivery_outbox")
    op.drop_index("ix_delivery_outbox_ticket_direction_status", table_name="delivery_outbox")
    op.drop_index("ix_delivery_outbox_stale", table_name="delivery_outbox")
    op.drop_index("ix_delivery_outbox_claim", table_name="delivery_outbox")
    op.drop_table("delivery_outbox")
    op.drop_table("user_identities")
    op.drop_index("ix_tickets_status_updated", table_name="tickets")
    op.drop_index("ix_tickets_status_last_activity", table_name="tickets")
    op.drop_table("tickets")
    op.drop_table("users")
    op.drop_table("system_settings")
    op.drop_index("ix_quick_responses_state_deadline", table_name="quick_responses")
    op.drop_table("quick_responses")
    op.drop_table("operator_dashboard_state")
    op.drop_index("ix_inbound_updates_stale", table_name="inbound_updates")
    op.drop_index("ix_inbound_updates_ordering", table_name="inbound_updates")
    op.drop_index("ix_inbound_updates_claim", table_name="inbound_updates")
    op.drop_table("inbound_updates")
    op.drop_table("blocklist")
    # ### end Alembic commands ###
